{{- if .Values.ledgerService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "iof.fullname" . }}-ledger-service
  labels:
    {{- include "iof.componentLabels" (dict "component" "ledger-service" "root" .) | nindent 4 }}
spec:
  type: {{ .Values.ledgerService.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.ledgerService.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iof.componentSelectorLabels" (dict "component" "ledger-service" "root" .) | nindent 4 }}
{{- end }}
